services:
  db:
    image: postgres:16-alpine
    container_name: restaurant_db
    environment:
      POSTGRES_DB: thfamily18_restaurant
      POSTGRES_USER: thfamily18
      POSTGRES_PASSWORD: thfamily18@
    ports:
      - "5432:5432"
    volumes:
      - restaurant_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U thfamily18 -d thfamily18_restaurant"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant_app
    depends_on:
      db:
        condition: service_healthy
    #env_file:
    #  - .env
    environment:
      # Custom Spring profiles for Docker
      SPRING_PROFILES_ACTIVE: docker

      # DB connection
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/thfamily18_restaurant?currentSchema=public
      SPRING_DATASOURCE_USERNAME: thfamily18
      SPRING_DATASOURCE_PASSWORD: thfamily18@

      # Flyway (turn on clearly)
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
      SPRING_FLYWAY_BASELINE_VERSION: "1"
      SPRING_FLYWAY_SCHEMAS: public
      SPRING_FLYWAY_DEFAULT_SCHEMA: public

      # Hibernate: Use validation to catch schema deviations
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      # log flyway debug
      LOGGING_LEVEL_ORG_FLYWAYDB: INFO

      # Tuỳ bạn: Java memory flags
      JAVA_OPTS: "-XX:MaxRAMPercentage=75"
    ports:
      - "8080:8080"

volumes:
  restaurant_db_data:
