server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/thfamily18_restaurant
    username: thfamily18
    password: thfamily18@
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  threads:
    virtual:
      enabled: true

app:
  jwt:
    secret: "55396a037e2b8c4ec60407a11310a9490e0f650951188ece9b1994bfba046d15"
    issuer: "thfamily18"
    accessTokenMinutes: 60

  admin:
    email: "ducthuanle@threstaurant.de"
    password: "Tuanh2020@@@@"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

stripe:
  secretKey: ${STRIPE_SECRET_KEY}          # sk_test_...
  webhookSecret: ${STRIPE_WEBHOOK_SECRET}  # whsec_... (Stripe CLI listen hoáº·c dashboard)
