server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/thfamily18_restaurant?currentSchema=public
    username: thfamily18
    password: thfamily18@
# Updates should only be used in the Development (Dev) environment.
  # In a production environment, it's recommended to set it to none or validate and use DB version control tools like Liquibase or Flyway to ensure data security.
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public
    default-schema: public
    baseline-on-migrate: true
    baseline-version: 1
    validate-on-migrate: true
    baseline-description: "baseline existing schema (was hibernate ddl-auto update)"

  jpa:
    #defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  threads:
    virtual:
      enabled: true

logging:
  level:
    #org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG
    #org.springframework.boot.autoconfigure: DEBUG

app:
  jwt:
    secret: "55396a037e2b8c4ec60407a11310a9490e0f650951188ece9b1994bfba046d15"
    issuer: "thfamily18"
    accessTokenMinutes: 60

  admin:
    email: "ducthuanle@threstaurant.de"
    password: "Tuanh2020@@@@"

  payment:
    ttlMinutes: 30

  debugConfig: "HELLO_FLYWAY"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

stripe:
  secretKey: ${STRIPE_SECRET_KEY}          # sk_test_...
  webhookSecret: ${STRIPE_WEBHOOK_SECRET}  # whsec_... (Stripe CLI listen hoáº·c dashboard)
